[env]
OUTPUT_DIR = 'build'

[tasks.build]
run = "gogio --target js -o $OUTPUT_DIR ."
sources = ['main.go']
outputs = ["{{ get_env(name='OUTPUT_DIR') ~ '/*' }}"]

[tasks.clean]
run = "rm -rf $OUTPUT_DIR"
